### ISSUE TITLE
Make use of links

### ISSUE THREAD

**Issue by rlaemmel** [softlang/megalib#7]
/cc @MarcelH91 @AndrEm12 

In the JavaC example, it would make sense to start using links.

**Comment by dblM90** [comment]
what do you mean by saying "start using links"?

**Comment by rlaemmel** [comment]
3.2 The principle ‘Semantic annotations’
http://softlang.uni-koblenz.de/megaconnect/

![image](https://cloud.githubusercontent.com/assets/1208815/17456219/85c4ae20-5bd0-11e6-8379-0e544d8c4ab7.png)

Basically attach links to everything as much as possible.
(When I was checking your stuff, I didn't see any links yet.)

**Comment by dblM90** [comment]
There are links defined in the grammar, they are named descriptions. but i will rename it, because its confusing

**Comment by rlaemmel** [comment]
What I meant by "Make use of links" -- just starting making use of them in the examples :-)

**Comment by dblM90** [comment]
Oh i see :D 

it's wip now ;)

**Comment by dblM90** [comment]
maybe someone, who is expert in wirting regular expressions could give me a matching rule for antlr to resolve links

**Comment by MarcelH91** [comment]
The problem is that you'd have to write a matching regular expression for any URL. The regex for this would be too complex for my taste to put into an ANTLR grammar. Instead you can solve this by opening a connection to the url. This way you can also check whether the URL links to an existing web resource. http://stackoverflow.com/questions/1378199/how-to-check-if-a-url-exists-or-returns-404-with-java.

**Comment by AndrEm12** [comment]
I think that we could implement the url check very well in the standard checker,
but there still exists the problem, that ANTLR is reading our Megamodel completly, so that we need any Lexer/Parser rule for the url, because otherwise it would throw an exception, if I had understand ANTLR right.


I thought that we could simply allow "everything" as an input at the link in the grammar and as said before, the checker proves later, if it is a link.

**Comment by MarcelH91** [comment]
Yes, from here on I take over. I'm already working at it. :-)
